pipeline {
    // used for master/slave pipeline
    agent any

    // must needs to be presented on every Jenkinsfile
    tools {
        maven "MAVEN3"
        jdk "OpenJDK8"
    }

    stages {

        stage('Fetch code') {
            steps {
                git branch: 'main', url: 'https://github.com/Ajaytekam/codeRepo.git'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean install -DskipTests'  
            }
            post {
                success {
                    echo 'Now archiving it...'  
                    archiveArtifacts artifacts: '**/target/*.war'   
                }
            }
        }

    }
}
